apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: omkar
  namespace: flux-system
spec:
  interval: 5s
  path: ./apps/base/nginx
  prune: true
  timeout: 3m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  env:
    - name: MONGODB_USER
      valueFrom:
        secretKeyRef:
          name: basic-auth-sealed.yaml
          key: user
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: basic-auth-sealed.yaml
          key: password
          
