apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m0s
  releaseName: mongodb
  env:
    - name: MONGODB_USER
      valueFrom:
        secretKeyRef:
          name: basic-auth-sealed.yaml
          key: user
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: basic-auth-sealed.yaml
          key: password
